server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /demo-application

spring:
  application:
    name: "@project.name@"
    version: "@project.version@"
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
      type: batch
    consumer:
      group-id: default-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

gft:
  logs:
    path: ./logs
    application:
      name: ${spring.application.name}
  flow:
    activated: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  server:
    port: ${server.port}

logging:
  level:
    root: INFO

